[application]
default_platform = "desktop"

out_dir = "dist"

asset_dir = "assets"

[web.app]

# HTML title tag content
title = "tailwind"

index_on_404 = true

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["assets/tailwind.css"]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

[bundle]
identifier = "com.mycompany"
publisher = "Zhou Jiale"